<a href="https://colab.research.google.com/github/Harsh13964/Python-/blob/main/Harshpreet_Kaur.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 1

In [ ]:
# 1 Declare and print

name = "Harsh"
age = 21
course = "Artificial Intelligence"
print("Name:", name, " Age:", age, " Course:", course)

Name: Harsh  Age: 21  Course: Artificial Intelligence


In [ ]:
# 2 Swap two numbers
a=4
b=9
print("a=",b)
print("b=",a)

a= 9
b= 4


In [ ]:
# 3 Arithmetic operations
a=12
b=43
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a%b)

55
-31
0.27906976744186046
516
12


In [ ]:
#4 Take marks of five subjects and calculate the total and percentage
a=88
b=79
c=81
d=69
e=57

total=a+b+c+d+e
print(total)
percentage = total/500*100
print(percentage )

374
74.8


In [ ]:
#5 Use compound assignment operator
x=12
print (x)
x+=5
print (x)
x-=3
print (x)
x*=4
print (x)
x/=2
print(x)

12
17
14
56
28.0


In [ ]:
##6 Realational Operator check
a=442
b=443

if a==b:
  print ("both are equal")
elif a>b:
  print("First is greater")
else:
  print ("Second is greater")

Second is greater


In [ ]:
##7 Logical Operator challenge
is_raining = True
have_umbrella =False

print(is_raining & have_umbrella)

print(is_raining | have_umbrella )

if not is_raining or (is_raining and have_umbrella):
  print ("You can go outside.")
else:
  print ("You cannot go outside. ")


False
True
You cannot go outside. 


In [ ]:
##8 Identity operator
list1=[1,2,3]
list2=[1,2,3]
print(list1==list2)
print(list1 is list2)

True
False


In [ ]:
##9 Bitwise operator
a=27
b=42

print(a&b) #AND
print(a|b) #OR
print(a^b) #XOR

10
59
49


In [ ]:
##10 Variables type aand typecasting
a = 6.6
b = 7

print ("type of int_num:", type(a))
print("type of float_num:",type(b))

sum = a+b
print("sum as integer:",(sum))


type of int_num: <class 'float'>
type of float_num: <class 'int'>
sum as integer: 13.6


Assignment 2

In [ ]:
#1 To print number 1 to 10 but stop the loop when number reaches 9

for i in range(1,14):
  if i==11:
    break
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
##2 To print +ve numbers and show -ve numbers when user input -ve numbers.

number=int(input("Enter the number:"))
if number>=0:
 print(f"you entered:{number}")
else:
  print("Entered no is negtive")

Enter the number:-8
Entered no is negtive


In [ ]:
#3 To find first even nmber in the list using for loop and break

list=[3,9,33,22,53,89,8,62,75]
for l in list:
  if l % 2==0:
    print("First Even no found:",l)
    break

First Even no found: 22


In [ ]:
##4 Keep adding number onwards until total exceeds 25 print last sum and digit

A=[7,5,7,3,9,5,1,4,2,8,1]
total=0

for a in A:
  total=total+a
  if total>25:
    print("Total sum:",total)
    print("Last number added:",a)
    break

Total sum: 31
Last number added: 9


In [ ]:
#5 Keep asking the user to guess the password until they guess admin123 use while and break

while True:
  guessed_password = input("Enter the password:")
  if guessed_password=="admine123":
    print("Password is correct")
    break
  else:
    print("Wrong password ")

Enter the password:Harsh
Wrong password 
Enter the password:admine123
Password is correct


In [ ]:
##6 Give a number print each digit until a zero is found

number= input("Enter the number:")
for digit in number:
  if digit=="0":
    break
  print(digit)

Enter the number:4
4


In [ ]:
##7 To print multiple of 7

for i in range (1,11):
  print(f"7×{i}={7*i}")

7×1=7
7×2=14
7×3=21
7×4=28
7×5=35
7×6=42
7×7=49
7×8=56
7×9=63
7×10=70


Assignment 3

In [ ]:
#1 Take a sentence and reverse the order of its words. Example: "I love python" ➡️ "Python love I".

x=input("Enter the sentences:")
list1=x.split()
list2=list1[::-1]
x=' '.join(list2)

print("Reversed sentence:",x)

Enter the sentences:I love python 
Reversed sentence: python love I


In [ ]:
#2  Give a sting of consonant (non-vowels,ignoring case). Example "Hello World"➡️ 7(H,L,L,W,R,L,D).

x=input("Enter a string:")
vowels='aeiouAEIOU'
consonents=[i for i in x if i.isalpha() and i not in vowels ]
count=len(consonents)
print(f"{count}({','.join(consonents)})")

Enter a string:Hi my name is Harsh
10(H,m,y,n,m,s,H,r,s,h)


In [ ]:
# 3 Check if two strings are anagrams(same character, same frequency , ignoring case). Example:"Listen","Silent",-"Anagram","Hello" "World"-"Not Anagram "

x=input("Enter first string:")
y=input("Enter second string:")

s1=x.replace(" ","").upper()
s2=y.replace(" ","").upper()

if sorted(s1)==sorted(s2):
  print("Anagarm")
else:
  print("Not Anagram ")

Enter first string:Dog
Enter second string:God
Anagarm


In [ ]:
#4 Find the first character in a string that appear only once (case sensitive) . Exapmple "Swiss"-"w" "Programming"-"r".

x=input("Enter a string:")

s1=x.replace(" ","").upper()

for i in s1:
  if s1.count(i)==1:
    print(i)
    break
else:
  print("None")

Enter a string:Harsh
A


In [ ]:
# 5. Compress a string by replacing repeated characters with the character and count. Example: "aaabbcc" → "a3b2c2", If compressed string isn't shorter return orignal.

x = input("Enter a string: ")

if not x:
  print("")
else:
  compress =""
  count = 1
  for i in range(1,len(x)):
      if x[i]==x[i-1]:
          count +=1
      else:
          compress += x[i-1] + str(count)
          count = 1
  compress += x[-1] + str(count)

  if len(compress) < len(x):
    print("compressed string:", compress)
  else:
    print("no need to compress:",x)

Enter a string: aaaabbbbbbcccc
compressed string: a4b6c4


In [ ]:
#6 Find yhe longest substring in a string that is a palindrome(case sensitive). Example:"babad" - "bab"(or"aba"), "cbbd"- "bb".


s=input("Enter a string: ")
x=s.replace(" ","").upper()
n=len(x)

longest=""

for i in range(n):
  for j in range(1,n):
      substr=x[i:j+1]
      if substr == substr[::-1]:
        if len(substr) > len(longest):
           longest = substr
print("Longest palindrome: ",longest)

Enter a string: hhrrdd
Longest palindrome:  HH


In [ ]:
# 7. Gven a string containing only '(',').','{','}','[',']', check if the sequence is valid (properly nested and closed). Example: "[{()}]" → "Valid", "(]" → "Invalid".

x=input("Enter a string: ")
s=[]
dict={')':'(', ']':'[','}':'{' }
valid=True

for i in x:
  if i in '([{':
      s.append(i)
  elif i in ')]}':
    if not s or s[-1] != dict[i]:
      valid= False
      break
    s.pop()

if s:
  valid =False

print("Valid" if valid else "Invalid")

Enter a string: Harsh
Valid


In [ ]:
# 8. Given a start word, end word, and a list of valid words, find the mininmum number of steps to transform the word to the end word
#by changing one letter at a time, where each intermediate word must be in the list. All words are same length, lowercase.
# Example: start"hot", end="cog", wordlist=["hot","dot","dog",log","lot","cog"] → 5(hit → hot → dot → dog → cog), Return 0 if impossible.

from collections import deque
start = "hit"
end = "cog"
wordList = ["hot", "dot", "dog", "lot", "log", "cog"]
wordSet = set(wordList)
queue= deque([(start, 1)])
while queue:
  word, steps = queue.popleft()
  if word == end:
         print(steps)
         break
  for i in range(len(word)):
        for c in 'abcdefghijklmnopqrstuvwxyz':
            next_word = word[:i] + c + word[i+1:]
            if next_word in wordSet:
               wordSet.remove(next_word)
               queue.append((next_word, steps + 1))
else:
  print(0)

5


Assignment 4

In [ ]:
#1 Create a dictionary of 5 students with their names as keys and marks as values. Print all the keys and values.
my_dict= {"Raman":78,"Harsh":75,"Aman": 67,"Simran":84,"Gurkirat":79}
print(my_dict)

{'Raman': 78, 'Harsh': 75, 'Aman': 67, 'Simran': 84, 'Gurkirat': 79}


In [ ]:
#4 Merge two dictionaries and print the merged dictionary.
dict1= {'a':1,'b':6,'c':10,'d':4}
dict2=  {'e':11,'f':16,'g':5,'h':9}
dict3= dict1|dict2
print(dict3)

{'a': 1, 'b': 6, 'c': 10, 'd': 4, 'e': 11, 'f': 16, 'g': 5, 'h': 9}


In [ ]:
#5 Create a dictionary where the keys are numbers between 1 and 10, and the values are their squares
sq={num:num**2 for num in range(1,11)}
print(sq)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [ ]:
#6 Write a program that inverts a dictionary (i.e., swaps keys and values). Assume all values are unique.
dict={'a':1,'b':6,'c':10,'d':4,'e':9}
inverted_dict={value: keys for keys, value in dict.items() }
print(inverted_dict)

{1: 'a', 6: 'b', 10: 'c', 4: 'd', 9: 'e'}


In [ ]:
string= "hello world"
freq={}

for char in string:
    if char!= " ":
        freq[char]= freq.get(char,0)+1
print(freq)

{'h': 1, 'e': 1, 'l': 3, 'o': 2, 'w': 1, 'r': 1, 'd': 1}


In [ ]:
#7. Given a nested dictionary of students and their subject-wise marks, calculate and print the average marks for each student.
students={ "student1":{'phy':78, 'chem':65,'maths':89,'english': 85},
         "student2":{'phy':79, 'chem':67,'maths':76,'english': 66},
         "student3":{'phy':74, 'chem':55,'maths':84,'english': 98},
         "student4":{'phy':81, 'chem':45,'maths':88,'english': 75},
         "student5":{'phy':38, 'chem':35,'maths':69,'english': 95},
}

for name, subject in students.items():
    avg= sum(subject.values())/len(subject)
    print(name ," average is",avg)



student1  average is 79.25
student2  average is 72.0
student3  average is 77.75
student4  average is 72.25
student5  average is 59.25


In [ ]:
#8. Write a program to group words by their length from a list using a dictionary.
list=['red', 'blue','black','pink','green']
group={}
for word in list:
    l=len(word)
    group.setdefault(l,[]).append(word)

print(group)


{3: ['red'], 4: ['blue', 'pink'], 5: ['black', 'green']}


In [ ]:
#10. Create a program that takes a list of tuples (name, score) and builds a dictionary
#where each name is a key, and the value is a list of all their scores. Then calculate and print
#each person's average score.
list= [('Harsh',78),('Raman',88),('Komal',55),('Simran',90),('Harsh',74),('Raman',98),('Komal',59),('Simran',80)]
score_dict={}
for name,score in list:
    if name in  score_dict:
        score_dict[name].append(score)
    else:
        score_dict[name]=[score]
print(score_dict)
for name, score in score_dict.items():
    avg= sum(score)/len(score)
    print(name,"average is",avg)




{'Harsh': [78, 74], 'Raman': [88, 98], 'Komal': [55, 59], 'Simran': [90, 80]}
Harsh average is 76.0
Raman average is 93.0
Komal average is 57.0
Simran average is 85.0


Assignment 5

In [ ]:
#WAP to make a pyramid.
def pyramid(n, current=1):
    if current > n:
            return
    spaces = ' ' * (n - current)
    stars = '*' * (2 * current - 1)
    print(spaces + stars)
    pyramid(n, current + 1)

n=int(input("Enter no. of lines: "))
pyramid(n)

Enter no. of lines: 8
       *
      ***
     *****
    *******
   *********
  ***********
 *************
***************


In [ ]:
#Generate a pattern like:
'''
*
* *
* * *
* * * *
'''
def pattern(n, current=1):
    if(current>n):
     return
    print("*"* current)
    pattern(n, current+1)
n= int(input("Enter No.:"))
print(pattern(n))

Enter No.:7
*
**
***
****
*****
******
*******
None


In [ ]:
#Draw a sqaure pattern like star.
def square_pattern(n):
    for i in range(n):
        print("* " * n)

size = int(input("Enter the size of the square: "))
square_pattern(size)

Enter the size of the square: 9
* * * * * * * * * 
* * * * * * * * * 
* * * * * * * * * 
* * * * * * * * * 
* * * * * * * * * 
* * * * * * * * * 
* * * * * * * * * 
* * * * * * * * * 
* * * * * * * * * 


In [ ]:
#Draw a rectangle pattern like star.
#area of rectangle = lXb
def rectangle_pattern(l,b):
    for i in range(b):
        print("* " * l)
l= int(input("Enter the length of rectangle: "))
b= int(input("Enter the breadth of rectangle: "))
print(rectangle_pattern(l,b))

Enter the length of rectangle: 3
Enter the breadth of rectangle: 5
* * * 
* * * 
* * * 
* * * 
* * * 
None


Assignment 6

In [ ]:
#1.  Write a Python program to create a tuple with different data types and print its type.
tuple=('hello', 2, 3.14, True)
print(tuple)
print("type:", type(tuple))

('hello', 2, 3.14, True)
type: <class 'tuple'>


In [ ]:
#2. Given a tuple t = (10, 20, 30, 40, 50), write a program to access the second last element.
t = (10, 20, 30, 40, 50)
second_last= t[-2]
print("second last elemnt is:",second_last)

second last elemnt is: 40


In [ ]:
# 3. Write a program to count the number of times a given element appears in a tuple.
tuple=(2,5,7,8,10,3,5,8,7,12,10,3,8,0)
my_set = tuple.count(10)
print(my_set)

2


In [ ]:
#4. Write a program to convert a tuple of strings into a single string. Example: ('Python', 'is', 'fun') --> 'Python is fun'
tuple=('Python', 'is', 'fun')
single_string= ' '.join(tuple)
print (single_string)

Python is fun


In [ ]:
# 6. Write a Python program to create two sets and perform union, intersection, and difference operations.
set1={'apple', 'mango','banana','chiku', 'papaya','kiwi','melon'}
set2={'muskmelon', 'strawberry','kiwi','melon'}

union = set1.union(set2)
print("union:", union)
intersection = set1.intersection(set2)
print("intersection:", intersection)
difference = set1.difference(set2)
print("difference:", difference)

union: {'mango', 'kiwi', 'apple', 'muskmelon', 'chiku', 'strawberry', 'papaya', 'melon', 'banana'}
intersection: {'melon', 'kiwi'}
difference: {'mango', 'apple', 'chiku', 'papaya', 'banana'}


In [ ]:
#7. Write a program to check if a given element is present in a set or not
set ={'apple', 'mango','banana','chiku', 'papaya','kiwi','melon'}
element = input("Enter an element to check: ")

if element in set:
    print(f"{element} is \'present\' in the set.")
else:
    print(f"{element} is \'NOT present\' in the set.")

Enter an element to check: Guava
Guava is 'NOT present' in the set.


In [ ]:
#8. Write a program to remove duplicate elements from a list using a set.

list = [10, 20, 10, 30, 40, 20, 60,50,40,20]
unique_list = set(list)

print("Original List:", list)
print("List after removing duplicates:", unique_list)

Original List: [10, 20, 10, 30, 40, 20, 60, 50, 40, 20]
List after removing duplicates: {40, 10, 50, 20, 60, 30}


In [ ]:
#9. Write a Python program to find the symmetric difference between two sets.
set1={'apple', 'mango','banana','chiku', 'papaya','kiwi','melon'}
set2={'muskmelon', 'strawberry','kiwi','melon'}
symmetric_diff = set1.symmetric_difference(set2)
print(symmetric_diff)

{'mango', 'apple', 'muskmelon', 'chiku', 'strawberry', 'papaya', 'banana'}


In [ ]:
#10. Given a list of numbers, write a Python program to find all unique elements using sets.
list=[2,1,5,4,6,3,2,4,8,6,9,2]
unique_elements=set(list)
print("Original List:", list)
print("Unique Elements:", unique_elements)

Original List: [2, 1, 5, 4, 6, 3, 2, 4, 8, 6, 9, 2]
Unique Elements: {1, 2, 3, 4, 5, 6, 8, 9}


Assignment 7

In [ ]:
#1. Write a function to find the factorial of a number using recursion.
def fact(n):
   if n < 0:
      return "Factorial is not defined for negative numbers"
   elif n == 0 or n == 1:
      return 1
   else:
      result = 1
      for i in range(2, n + 1):
          result *= i
      return result
print(fact(9))

362880


In [ ]:
#2. Write a function that checks whether a number is prime or not.
def is_prime(n):
   if n <= 1:
      return False
   for i in range(2, int(n**0.5) + 1):
       if n % i == 0:
           return False
   return True
print(is_prime(7))

True


In [ ]:
#3. Create a function that takes a string as input and returns the number of vowels in it.
def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0
    for char in s:
        if char in vowels:
           count += 1
    return count
print(count_vowels("Hello Myself Harshpreet Kaur"))

8


In [ ]:
# 4. Write a function that accepts a list of numbers and returns the maximum and minimum values.
def find_max_min(numbers):
   if not numbers:
      return None
   max_num = min_num = numbers[0]
   for num in numbers:
       if num > max_num:
          max_num = num
       if num < min_num:
          min_num = num
   return max_num, min_num
print(find_max_min([3, 1, 4, 1, 5, 9, 2, 6]))

(9, 1)


In [ ]:
#5. Write a Python function to calculate the nth Fibonacci number using recursion.
def fibonacci(n):
   if n <= 0:
      return []
   elif n == 1:
      return [0]
   elif n == 2:
      return [0, 1]

   fib_series = [0, 1]
   for i in range(2, n):
       next_value = fib_series[i - 1] + fib_series[i - 2]
       fib_series.append(next_value)
   return fib_series
n= int(input("Enter no: "))
print(fibonacci(n))

Enter no: 7
[0, 1, 1, 2, 3, 5, 8]


In [ ]:
import math
def find_gcd(a, b):
    return math.gcd(a, b)
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print("The GCD is:", find_gcd(num1, num2))

Enter first number: 43
Enter second number: 31
The GCD is: 1


In [ ]:
#7. Write a function that takes a list and returns a new list with only unique elements.
def unique_elements(lst):
    unique_set = set(lst)
    return list(unique_set)

my_list = [1, 2, 2, 3, 4, 4, 5]
print(unique_elements(my_list))


TypeError: 'list' object is not callable

In [ ]:
#9. Write a function that takes a number and returns True if it is a palindrome, otherwise False.
def is_palindrome(n):
   str_n = str(n)
   return str_n == str_n[::-1]
n=int(input("Enter No.: "))
print(is_palindrome(n))

Enter No.: 65
False


In [ ]:
# 10. Create a function that takes a temperature in Celsius and returns it in Fahrenheit
#formulaa: c/5=(f-32)/9
def f_to_c(f):
    return 5*(f-32)/9
f=int(input("Enter tempreature:"))
c=f_to_c(f)
print(f"{round(c,3)}, degree celsisus")

#method 2
def celsius_to_fahrenheit(celsius):
   return (celsius * 9/5) + 32
celsisus= int(input("Enter tempreature:"))
print(celsius_to_fahrenheit(celsisus))


Enter tempreature:89
31.667, degree celsisus
Enter tempreature:98
208.4


Assignment 8

In [ ]:
#1 Write a Python program to create a new text file and write the text 'Hello, File Handling!' to it.

with open("newfile.txt","w") as f:
  f.write("Hello,File Handling!")
print("File written successful.")

File written successful.


In [ ]:
# 2. Write a Python program to read the contents of 'example.txt' and display them on the screen

from google.colab import files
uploaded = files.upload()

with open("example.txt","r")as f:
content=f.read()
print(content)

In [ ]:
#3. Write a Python program to count the number of words in a given text file

# Count number of words in example.txt
with open("example.txt", "r", encoding="latin-1") as f:   # ← adjust encoding if needed
    text = f.read()

words = text.split()
print("Number of words:", len(words))

Number of words: 626805


In [ ]:
#4. Write a Python program to read a file and print only

with open("sample.txt","r") as f:
  for line in f:
    if line.startswith('A'):
      print(line.stip())

In [ ]:
# 5.Write a Python program to merge the contents of two files into a third file.

with open("sample.txt", "r") as f1, open("products.txt", "r") as f2:
  with open("merged.txt", "w")as f3:

    f3.write(f1.read())
    f3.write(f2.read())

print("Files merged successfully.")



Files merged successfully.


In [ ]:
#6 Write a Python program that reads a text file and prints its content in reverse order (last line first).


with open("sample.txt", "r") as f:
  lines=f.readlines()
  for line in reversed(lines):
    print(line.strip())

Eve,32,HR
David,28,Engineering
Charlie,35,Sales
Bob,25,Marketing
Harsh,30,Engineering
Name,Age,Department


In [ ]:
#7 Write a Python program to find and replace a word in a file (e.g., replace 'old' with 'new').

with open("sample.txt", "r") as f:
 content = f.read()
content = content.replace("Alice","Harsh")
with open("sample.txt", "w") as f:
 f.write(content)

In [ ]:
#8 Write a Python program to create a log file and append timestamps whenever the program is run.

from datetime import datetime
with open("logfile.txt", "a") as log:
 log.write(f"Program run at: {datetime.now()}\n")

In [ ]:
#9 Write a Python program to store and read student records (name and marks) from a file.

with open("students.txt", "w") as f:
 f.write("Alice 85\nBob 90\nCharlie 78")
with open("students.txt", "r") as f:
 for line in f:
     name, marks = line.strip().split()
     print(f"Name: {name}, Marks: {marks}")

Name: Alice, Marks: 85
Name: Bob, Marks: 90
Name: Charlie, Marks: 78


In [ ]:
#10 Write Python program to copy an image file (binary mode) from one location to another.

with open("pinterest.jpg", "rb") as src, open("pinterest.jpg", "wb") as dest:
 dest.write(src.read())

Assignment 9

In [ ]:
# 1. Create a NumPy array with values from 1 to 10. Print the shape, dimension, and data type of the array.

import numpy as np
arr=np.arange(1,11)
print("Array:",arr)
print("Shape:",arr.shape)
print("Dimension:",arr.ndim)
print("Data type:",arr.dtype)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Dimension: 1
Data type: int64


In [ ]:
#2 Create a 3x3 NumPy array of all zeros and another of all ones. Then create a 3x3 identity matrix.

zeros=np.zeros((3,3))
ones=np.ones((3,3))
identity=np.identity(3)
print("Zeros:\n",zeros)
print("Ones:\n",ones)
print("Identity:\n", identity)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#3. Generate an array of 15 random integers between 10 and 100 using np.random.randint. Reshape it into a 3x5 matrix and print it.

arr=np.random.randint(10,100,15).reshape(3,5)
print("Random 3×5 Matrix:\n",arr)

Random 3×5 Matrix:
 [[53 64 75 11 56]
 [38 22 98 32 37]
 [87 55 31 97 78]]


In [ ]:
#4 Create a NumPy array from 1 to 20. Extract every 3rd element starting from index 1 using slicing.

arr=np.arange(1,21)
result=arr[1::3]
print("Every 3rd element from index 1:",result)

Every 3rd element from index 1: [ 2  5  8 11 14 17 20]


In [ ]:
#5 Create two arrays: a = np.array([2, 4, 6, 8]) and b = np.array([1, 3, 5, 7]). Perform element-wise addition,multiplication, and compare which elements in a are greater than in b.

a=np.array([2,4,6,8])
b=np.array([1,3,9,7])
print("Addition:",a+b)
print("Multiplication:",a*b)
print("a>b:",a>b)

Addition: [ 3  7 15 15]
Multiplication: [ 2 12 54 56]
a>b: [ True  True False  True]


In [ ]:
#6 Create a NumPy array with 20 random values (0 to 1) using np.random.rand(). Find the mean, median,standard deviation, min, and max

arr=np.random.rand(20)
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Std Dev:",np.std(arr))
print("Min:",np.min(arr))
print("Max:", np.max(arr))

Mean: 0.5580178640720768
Median: 0.6374744579928397
Std Dev: 0.27080712949847663
Min: 0.0502118631969688
Max: 0.9491967720905602


In [ ]:
#7 Given: arr = np.array([[3, 5], [7, 9]]). Find the sum across rows and columns using axis.

arr=np.array([[3,5],[7,9]])
print("Sum across rows:",arr.sum(axis=1))
print("Sum across column:",arr.sum(axis=0))

Sum across rows: [ 8 16]
Sum across column: [10 14]


In [ ]:
#8 Create a NumPy array of numbers from 10 to 30. Filter and print only the even numbers using boolean indexing.

arr=np.arange(10,31)
even=arr[arr%2==0]
print("Even numbers:",even)

Even numbers: [10 12 14 16 18 20 22 24 26 28 30]


In [ ]:
#9 Generate an array of 10 random integers from 1 to 100. Replace all elements greater than 50 with -1.

arr=np.random.randint(1,101,10)
arr[arr>50]=-1
print("Modified array:",arr)

Modified array: [44 -1 -1 32 37 -1 -1 -1 27 21]


In [ ]:
#10 Create two arrays: x = np.array([[1, 2], [3, 4]]) and y = np.array([[5, 6], [7, 8]]). Stack them vertically and horizontally, then flatten the result into a 1D array.

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v_stack = np.vstack((x, y))
h_stack = np.hstack((x, y))
flattened = h_stack.flatten()
print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)
print("Flattened:", flattened)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Flattened: [1 2 5 6 3 4 7 8]


Assignment 10

In [ ]:
#1. Load the dataset and display the first 10 rows.

import pandas as pd
df=pd.read_csv('diamonds.csv')
print(df.head(10))

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39


In [ ]:
##2. Check the shape and column names of the dataset.

import pandas as pd

# Load the dataset (replace with your actual file)
df = pd.read_csv('diamonds.csv')

# Check the shape of the dataset (rows, columns)
print("Shape of the dataset:", df.shape)

# Check the column names
print("Column names:", df.columns.tolist())

Shape of the dataset: (50000, 10)
Column names: ['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y', 'z']


In [ ]:
#3 Find and fill missing numeric values with their respective column means

import pandas as pd
df = pd.read_csv('diamonds.csv')
df.fillna(df.mean(numeric_only=True), inplace=True)
df.to_csv('filled_with_means.csv', index=False)
print(df)

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
49995   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
49996   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
49997   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
49998   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
49999   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[50000 rows x 10 columns]


In [ ]:
#4 Filter rows where `cut` is "Ideal" and `color` is "E".

import pandas as pd
df = pd.read_csv('diamonds.csv')

filtered = df.query("cut == 'Ideal' and color == 'E'")

In [ ]:
#5. Group by `cut` and compute the average `price` for each group.

# average price for each cut category
avg_price_by_cut = (
    df.groupby('cut', as_index=False)['price']
     .mean()                       # compute the mean
     .rename(columns={'price': 'avg_price'})  # optional: clearer name
                )

print(avg_price_by_cut)

         cut    avg_price
0       Fair  4329.705017
1       Good  3961.470266
2      Ideal  3463.090230
3    Premium  4607.382867
4  Very Good  3986.585594


In [ ]:
#6 Sort the data by `carat` in descending order and show the top 5 rows

import pandas as pd
top5 = df.nlargest(5, 'carat')
print(top5)


       carat      cut color clarity  depth  table  price      x      y     z
25426   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
25624   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
25163   4.13     Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
24102   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
24103   4.01  Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24


In [ ]:
#7 Convert the `price` column to a NumPy array and find its mean, median, and standard deviation

import numpy as np

price = df['price'].to_numpy()

mean_price   = price.mean()
median_price = np.median(price)
std_price    = price.std(ddof=0)

print(f"Mean price   : {mean_price:.2f}")
print(f"Median price : {median_price:.2f}")
print(f"Std. deviation: {std_price:.2f}")

Mean price   : 3944.81
Median price : 2410.00
Std. deviation: 3997.90


In [ ]:
#8. Count diamonds with `price > 5000` and `carat > 1` using NumPy conditions.

price = df['price'].to_numpy()
carat = df['carat'].to_numpy()

mask = (price > 5000) & (carat > 1)

count = np.sum(mask)

print(f"Number of diamonds with price > 5000 & carat > 1: {count}")

Number of diamonds with price > 5000 & carat > 1: 12798


In [ ]:
#9. Create a new column `price_updated` by increasing `price` by 10% using NumPy


df['price_updated'] = df['price'].to_numpy() * 1.10

print(df[['price', 'price_updated']].head())

   price  price_updated
0    326          358.6
1    326          358.6
2    327          359.7
3    334          367.4
4    335          368.5


In [ ]:
#10. Create a `volume` column as `x*y*z` and find the average `price` where `volume > 50`.

df.loc[:, 'volume'] = df['x'] * df['y'] * df['z']

average_price = df.loc[df['volume'] > 50, 'price'].mean()

print(f"Average price where volume > 50: {average_price:.2f}")


Average price where volume > 50: 4195.13
